### ISSUE TITLE
Mediapie

### ISSUE THREAD

**Issue by vksgoenka1** [developerrahulofficial/gesture-detetction#1]
Traceback (most recent call last):
  File "c:\Users\vikas\Downloads\code\Gesture-Recognition\main.py", line 2, in <module>
    import mediapipe as mp
  File "C:\Users\vikas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mediapipe\__init__.py", line 15, in <module>
    from mediapipe.python import *
  File "C:\Users\vikas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: DLL load failed while importing _framework_bindings: The specified module could not be found.

**Comment by sivashankarav** [comment]
uninstall ur current python and try with 3.9 to 3.11 i suggest u to install 3.11 from microsft store! its working with 3.11 python
and let me know if it works or not
